import{mkdir,writeFile}from'node:fs/promises';import{ACTIVITIES,AGE_15_PLUS_SHARE,VERIFIED_POPULATION}from'../src/model.js';
const OUT=new URL('../public/data/',import.meta.url);await mkdir(OUT,{recursive:true});
const TF='https://www150.statcan.gc.ca/t1/wds/sdmx/statcan/rest/data/DF_45100105',POP='https://www150.statcan.gc.ca/t1/wds/rest/getDataFromVectorsAndLatestNPeriods',AGE='https://www150.statcan.gc.ca/t1/wds/sdmx/statcan/rest/data/DF_17100005/1.1.1+7+13+19?lastNObservations=1';
const WEATHER='https://api.weather.gc.ca/collections/weather-alerts/items?f=json&limit=12',OG='https://open.canada.ca/data/en/api/3/action/recently_changed_packages_activity_list?limit=8',BANK='https://www.bankofcanada.ca/valet/observations/FXUSDCAD/json?recent=1';
const V={canada:1,nl:2,pe:3,ns:4,nb:5,qc:6,on:7,mb:8,sk:9,ab:10,bc:11,yt:12,nt:14,nu:15};
async function get(url,opt){const r=await fetch(url,opt);if(!r.ok)throw new Error(`${url} -> ${r.status}`);return r}
function blocks(xml){return xml.match(/<generic:Series>[\s\S]*?<\/generic:Series>/g)||[]}
function fld(b,id){return b.match(new RegExp(`id="${id}" value="([^"]+)"`,'i'))?.[1]}
async function timeUse(){const times=Array.from({length:288},(_,i)=>i+1).join('+'),acts=ACTIVITIES.map(a=>a.code).join('+'),url=`${TF}/1.${acts}.${times}.2+3.1.1`,xml=await(await get(url,{headers:{accept:'application/vnd.sdmx.genericdata+xml;version=2.1, application/xml'}})).text(),out={generatedAt:new Date().toISOString(),source:{agency:'Statistics Canada',table:'45-10-0105-01',dataflow:'DF_45100105',url:'https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=4510010501'},weekdays:{},weekends:{}},key=Object.fromEntries(ACTIVITIES.map(a=>[a.code,a.key]));
for(const b of blocks(xml)){const a=key[fld(b,'Activity_group')],t=fld(b,'Time_of_day'),d=fld(b,'Type_of_day'),v=Number(b.match(/<generic:ObsValue value="([^"]+)"/i)?.[1]);if(!a||!t||!Number.isFinite(v))continue;const bucket=d==='2'?out.weekdays:d==='3'?out.weekends:null;if(bucket)(bucket[t]||={})[a]=v}
for(const n of['weekdays','weekends']){if(Object.keys(out[n]).length!==288)throw new Error(`${n} has ${Object.keys(out[n]).length}/288`);for(let i=1;i<=288;i++){const s=out[n][String(i)];for(const a of ACTIVITIES)if(!Number.isFinite(s?.[a.key]))throw new Error(`${n} ${i} missing ${a.key}`)}}
await writeFile(new URL('time-use-profile.json',OUT),JSON.stringify(out));console.log('time-use: ok')}
async function ageShare(){const xml=await(await get(AGE,{headers:{accept:'application/vnd.sdmx.genericdata+xml;version=2.1, application/xml'}})).text(),vals={};for(const b of blocks(xml)){const c=fld(b,'Age_group'),v=Number(b.match(/<generic:ObsValue value="([^"]+)"/i)?.[1]);if(c&&Number.isFinite(v))vals[c]=v}for(const c of['1','7','13','19'])if(!Number.isFinite(vals[c]))throw new Error('age table missing '+c);return{share:(vals['1']-vals['7']-vals['13']-vals['19'])/vals['1'],allAges:vals['1'],under15:vals['7']+vals['13']+vals['19']}}
async function population(){try{const body=JSON.stringify(Object.values(V).map(vectorId=>({vectorId,latestN:1}))),rows=await(await get(POP,{method:'POST',headers:{accept:'application/json','content-type':'application/json'},body})).json(),rev=new Map(Object.entries(V).map(([k,v])=>[Number(v),k])),values={},periods=new Set;for(const row of rows){const id=rev.get(Number(row?.object?.vectorId)),p=row?.object?.vectorDataPoint?.filter(x=>Number.isFinite(Number(x?.value)))?.sort((a,b)=>String(b.refPer).localeCompare(String(a.refPer)))?.[0];if(id&&p){values[id]=Number(p.value);periods.add(String(p.refPer))}}for(const id of Object.keys(V))if(!Number.isFinite(values[id]))throw new Error('missing '+id);const age=await ageShare(),canada=values.canada;delete values.canada;const out={strategy:'live-wds',generatedAt:new Date().toISOString(),asOf:[...periods].sort().at(-1),canada,values,age15PlusShare:age.share,ageDenominator:age,source:{agency:'Statistics Canada',populationTable:'17-10-0009-01',ageTable:'17-10-0005-01'}};await writeFile(new URL('population.json',OUT),JSON.stringify(out));console.log('population: ok')}catch(e){await writeFile(new URL('population.json',OUT),JSON.stringify({...VERIFIED_POPULATION,generatedAt:new Date().toISOString(),age15PlusShare:AGE_15_PLUS_SHARE,fallbackReason:String(e.message||e)}));console.warn('population fallback:',e.message)}}
async function live(){const all=await Promise.allSettled([fetch(WEATHER).then(r=>r.json()),fetch(OG).then(r=>r.json()),fetch(BANK).then(r=>r.json())]);const [w,o,b]=all.map(x=>x.status==='fulfilled'?x.value:null),weather={status:w?'ready':'error',numberMatched:w?.numberMatched??w?.features?.length??0,items:(w?.features||[]).slice(0,8).map(f=>({id:f.id,name:f.properties?.alert_short_name_en||f.properties?.alert_name_en,feature:f.properties?.feature_name_en,province:f.properties?.province,risk:f.properties?.risk_colour_en,published:f.properties?.publication_datetime}))},openGovernment={status:o?.success?'ready':'error',items:(o?.result||[]).slice(0,8).map(r=>({timestamp:r.timestamp,id:r.object_id,title:r.data?.package?.title_translated?.en||r.data?.package?.title||r.data?.package?.name||'Updated dataset',organization:r.data?.package?.organization?.title||r.data?.package?.owner_org||'',url:`https://open.canada.ca/data/en/dataset/${r.object_id}`}))},row=b?.observations?.at(-1),bank={status:row?.FXUSDCAD?.v?'ready':'error',date:row?.d||null,value:Number(row?.FXUSDCAD?.v)||null,description:b?.seriesDetail?.FXUSDCAD?.description||'Daily average USD/CAD'};await writeFile(new URL('live-signals.json',OUT),JSON.stringify({generatedAt:new Date().toISOString(),weather,openGovernment,bank}));console.log('signals: ok')}
await Promise.all([timeUse(),population(),live()]);
